### ISSUE TITLE
web-app blank page

### ISSUE THREAD

**Issue by efraimkaov** [danielgarthur/neanes-web-app#1]
Where is the source code for **neanes-web-app**?
When I open in Browser **index.html** from **gh-pages** branch, I get just a blank page!

**Comment by danielgarthur** [comment]
This repo is only for deployment and hosting of the web app.

The source code is in https://github.com/danielgarthur/neanes. Electron apps can easily be compiled as normal web pages with some slight modifications (if/else checks to turn on/off various features).

If you want to run the web version locally, then run `npm run serve` instead of `npm run electron:serve`.
